SELECT  ID_USER AS UserId, PWD_USER AS HashedPassword, NAME_USER AS Name, TEXT_EMAIL AS Email, 
        CODE_USERCLASS AS UserClass, 
        CASE WHEN YN_PWDCHANGE = N'Y'
         THEN 1 ELSE 0 END AS ChangePassword, 
        CASE WHEN YN_LOCKED = N'Y' THEN 1 ELSE 0 END AS Locked
FROM    SA_USER_H
WHERE   ID_USER = @ID_USER
  AND   YN_USE = N'Y'
  AND   (DATE_END IS NULL OR DATEADD(DAY, 1, DATE_END) <= GETDATE())